name: button_future
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0-47.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  sliding_up_panel: ^2.0.0+1
  glass: ^1.0.1+1
  firebase_core: ^1.21.1
  provider: ^6.0.3
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  firebase_auth: ^3.7.0
  dartz: ^0.10.1
  auto_route: ^5.0.1
  uuid: ^3.0.6
  google_nav_bar: ^5.0.6
  lottie: ^1.4.2
  shimmer: ^2.0.0
  cloud_firestore: ^3.4.7
  flutter_zoom_drawer: ^3.0.3
  fade_out_particle: ^1.2.1
  avatar_glow: ^2.0.2
  equatable: ^2.0.5
  google_sign_in: ^5.4.2
  url_launcher: ^6.1.7
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.2
  build_runner: ^2.2.0

flutter:
  uses-material-design: true

  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Regular.ttf
        - asset: fonts/Gilroy-Thin.ttf
          weight: 200
        - asset: fonts/Gilroy-Light.ttf
          weight: 300
        - asset: fonts/Gilroy-Medium.ttf
          weight: 400
        - asset: fonts/Gilroy-SemiBold.ttf
          weight: 500
        - asset: fonts/Gilroy-Bold.ttf
          weight: 600
        - asset: fonts/Gilroy-ExtraBold.ttf
          weight: 700
        - asset: fonts/Gilroy-Black.ttf
          weight: 800
        - asset: fonts/Gilroy-Heavy.ttf
          weight: 900
